### ISSUE TITLE
Usage with GitLab CI/any CI

### ISSUE THREAD

**Issue by morremeyer** [alessandrojcm/commitlint-pre-commit-hook#36]
Hey, I’m struggling to incorporate a working `pre-commit` invocation into a CI pipeline that also invokes commitlint.

Running `pre-commit --hook-stage commit-msg` (when commitlint is registered for that stage) only produces an

```
[ERROR] `--commit-msg-filename` is required for `--hook-stage commit-msg`
``` 

Howover, I do not have a commit message file as I’m not currently producing a commit. Is there a way to overcome this? I’m specifically looking at GitLab CI, but I think once I understand the problem, the solution might be able to be generalized.

**Comment by alessandrojcm** [comment]
Hi there! If you are not producing a commit seems like you don't need to run commitlint at all. If that's the case, you can set the `SKIP` variable in your CI environment as per the [pre-commit docs](https://pre-commit.com/#temporarily-disabling-hooks). Now, if that's not the case and you still need to run commitlint regardless, please do explain a little more your use-case so we can reach a solution.

**Comment by alessandrojcm** [comment]
Alright, I understand. I think this would be doable with a shell script, I don't know specifically how the GitLab CI/CD system works; so I'll outline the general steps here: 

* Get the commit tags between the tip of the base branch and the tip of the branch you want to merge
* Get the commit messages: `git log --format=%B tag1...tag2` (you could add the `--no-merge` flag to not print the merge commits)
* Echo previous step to a temporary file `git log --format=%B tag1...tag2 > commit-msg`
* Then you can pass that file to `pre-commit`: `pre-commit --commit-msg-filename ./commit-msg`

Hope this helps!

**Comment by alessandrojcm** [comment]
Hey @morremeyer, just to keep track; was this helpful, or did you manage to solve it in another way?

**Comment by morremeyer** [comment]
I didn’t get to implement it yet, it definitely looks helpful. I will report back with a PR to add documentation once I got something working.
