### ISSUE TITLE
Be aware that commitlint v8.3.0 and onwards has a bug

### ISSUE THREAD

**Issue by htbvo** [alessandrojcm/commitlint-pre-commit-hook#5]
For more details, see: https://github.com/conventional-changelog/commitlint/issues/887
Until then, I recommend staying at commitlint 8.2.0

**Comment by alessandrojcm** [comment]
Looks like it was fixen in [8.3.4](https://github.com/conventional-changelog/commitlint/pull/888). I'll update it as soon as I get into my computer.

**Comment by alessandrojcm** [comment]
Done in 6bc8fdadc259830d59d9904dc22b7fe0d3ffb49a, thanks for the heads up!
