### ISSUE TITLE
Error:  Please add rules to your commitlint.config.js

### ISSUE THREAD

**Issue by yinzixie** [alessandrojcm/commitlint-pre-commit-hook#63]
I am using this configuration: 
```
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v6.0.0
    hooks:

    -   id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
```

Why do I still get this error?
✖   Please add rules to your `commitlint.config.js`

**Comment by alessandrojcm** [comment]
Hi there, could you post the contents of your `commitlint.config.js` please?

**Comment by yinzixie** [comment]
I thought we don't need this file since the config exists : `additional_dependencies: ["@commitlint/config-conventional"]`.

**Comment by yinzixie** [comment]
Thanks, but if I have to manually add this in `comitling.config.js` what's role of the `additional_dependencies` param ?

**Comment by alessandrojcm** [comment]
Shareable configurations need to be installed separately from NPM since they are not included with committint, with `additional_dependencies` we tell `pre-commit` to [install them](https://pre-commit.com/#config-additional_dependencies) along with `@commitlint/cli`; so is basically the equivalent of doing `npm i @commitlint/cli @commitlint/config-conventional`. Were you able to get it working with the `commitlint.config.js`?

**Comment by yinzixie** [comment]
That's weird. I still got this error after creating `comitling.config.js` 😢

**Comment by yinzixie** [comment]
Thanks @alessandrojcm it works!

**Comment by pvardanis** [comment]
@alessandrojcm still doesn't work for me.

Here's my `commitlint.config.js`:
```
//comitling.config.js at the root of your repo
module.exports = {
    extends: ['@commitlint/config-conventional'], // => commitlint/config-conventional
};
```

and here's my `.pre-commit-config.yaml`:
```
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
```

when I do a commit I get the following:
```
⧗   input: foo: bar
✖   Please add rules to your `commitlint.config.js`
    - Getting started guide: https://commitlint.js.org/#/?id=getting-started
    - Example config: https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js [empty-rules]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

Any help would be much appreciated.

**Comment by alessandrojcm** [comment]
> @alessandrojcm still doesn't work for me.
> 
> Here's my `commitlint.config.js`:
> 
> ```
> //comitling.config.js at the root of your repo
> module.exports = {
>     extends: ['@commitlint/config-conventional'], // => commitlint/config-conventional
> };
> ```
> 
> and here's my `.pre-commit-config.yaml`:
> 
> ```
> - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
>     rev: v9.4.0
>     hooks:
>       - id: commitlint
>         stages: [commit-msg]
>         additional_dependencies: ["@commitlint/config-conventional"]
> ```
> 
> when I do a commit I get the following:
> 
> ```
> ⧗   input: foo: bar
> ✖   Please add rules to your `commitlint.config.js`
>     - Getting started guide: https://commitlint.js.org/#/?id=getting-started
>     - Example config: https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js [empty-rules]
> 
> ✖   found 1 problems, 0 warnings
> ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
> ```
> 
> Weird thing is though that `echo 'foo: bar' | commitlint` works fine:
> 
> ```
> ❯ echo 'foo: bar' | commitlint
> 
> ⧗   input: foo: bar
> ✖   type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test] [type-enum]
> 
> ✖   found 1 problems, 0 warnings
> ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
> ```
> 
> Any help would be much appreciated.

Sorry @pvardanis bit busy right now, will get back to you ASAP

**Comment by cope** [comment]
The same just happened after upgrading 18.6.0 => 18.6.1

```
✖   Please add rules to your `commitlint.config.js`
    - Getting started guide: https://commitlint.js.org/#/?id=getting-started
    - Example config: https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/src/index.ts [empty-rules]
✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

**Comment by ThePlastic** [comment]
Same here upgrading from 18.6.0 to 18.6.1
Downgrade back to 18.6.0 for both "@commitlint/cli" and "@commitlint/config-conventional" everithing work again.

As additional information I can say that I use it on a NUXT project divided into layers, in the base layer 18.6.1 did not give any problems, but updating the other layers gave the error

**Comment by rotivleal** [comment]
Same. 18.6.1 gives me `Please add rules to your `commitlint.config.js` although it exists. Downgrading to 18.6.0 fixed it.

**Comment by alessandrojcm** [comment]
Hi all, which version of the hook are you using? The latest version of the hook [v9.11.0](https://github.com/alessandrojcm/commitlint-pre-commit-hook/releases/tag/v9.11.0) has `commitlint@18.4.3`, could you test with that one?

**Comment by ThePlastic** [comment]
> Hi all, which version of the hook are you using? The latest version of the hook [v9.11.0](https://github.com/alessandrojcm/commitlint-pre-commit-hook/releases/tag/v9.11.0) has `commitlint@18.4.3`, could you test with that one?

I'm using husky for the pre-commit-hook

**Comment by alessandrojcm** [comment]
> > Hi all, which version of the hook are you using? The latest version of the hook [v9.11.0](https://github.com/alessandrojcm/commitlint-pre-commit-hook/releases/tag/v9.11.0) has `commitlint@18.4.3`, could you test with that one?
> 
> I'm using husky for the pre-commit-hook

This is a hook for the `pre-commit` python package, not sure how you are using it with `husky`?

I will try to debug this issue with `commitlint` directly, it looks like it might be an issue with `commitlint` rather than this hook.

**Comment by ThePlastic** [comment]
> 
> This is a hook for the `pre-commit` python package, not sure how you are using it with `husky`?
> 
> I will try to debug this issue with `commitlint` directly, it looks like it might be an issue with `commitlint` rather than this hook.


Sorry, I wasn't sure what exactly you wanted to know.

I personally use commitlint in a NUXT project together with commitizen and husky

**Comment by stephenjason89** [comment]
> Same. 18.6.1 gives me `Please add rules to your `commitlint.config.js` although it exists. Downgrading to 18.6.0 fixed it. (I wasn't using the hook, though.)

Thank you. 
Temporarily downgrading to 18.6.0 fixes the problem.

I am using nuxt 3 with husky commit-msg hook

**Comment by alessandrojcm** [comment]
Hi all, just tested this with the latest hook version (which uses commitlint 18.6.1) and can confirm that it does indeed work properly. Please double check your commitlint config file, closing this.

**Comment by qidasheng369** [comment]
// commitlint.config.js

export default { }. 
will error. 
msg：
⧗   input: chore: init初始化husky+commit-msg+limt
✖   Please add rules to your `commitlint.config.js`
    - Getting started guide: https://commitlint.js.org/guides/getting-started


module.exports = {}
will ok.
[master a912ba7] build: commit-msg添加自定义设置
 1 file changed, 8 insertions(+), 8 deletions(-)


[#1986](https://github.com/conventional-changelog/commitlint/issues/1986#issuecomment-1011967692)
